const menuList = [
    {
        title:'首页',
        key:'/home'
    },
    {
        title:'公共基础',
        key:'/manager',
        children:[
            {
                title:'用户管理',
                key:'/manager/user',
            },
            {
                title:'角色管理',
                key:'/manager/permission'
            },
            {
                title:'菜单管理',
                key:'/manager/menu'
            },
        ]
    },
    {
        title:'活动管理',
        key:'/activity',
        children:[
            {
                title:'活动列表',
                key:'/activity/list'
            }
        ]
    },
    {
        title:'用户管理',
        key:'/user',
        children:[
            {
                title:'用户列表',
                key:'/user/list'
            }
        ]
    },
    {
        title:'游戏管理',
        key:'/game',
        children:[
            {
                title:'游戏列表',
                key:'/game/list'
            },
            {
                title:'奖品列表',
                key:'/game/prize'
            }
        ]
    },
    {
        title:'广告管理',
        key:'/banner',
        children:[
            {
                title:'广告展览',
                key:'/banner/view'
            },
            {
                title:'广告列表',
                key:'/banner/list'
            }
        ]
    }

];
export default menuList;